### ISSUE TITLE
您好，我想向您讨教一下关于NSP的问题

### ISSUE THREAD

**Issue by wangquent** [UMU618/blog#1]
在微软社区看到您当年对NSP排序问题的回复（https://social.msdn.microsoft.com/Forums/Windowsdesktop/en-US/de7ab4c3-2670-4e33-af68-f1367915ba8e/namespace-documentationusage-lupdualaddr-amp-lupaddrconfig?forum=windowssdk）
我在尝试了之后，确实在命令行中ping，能够解决排序问题，并且始终都能返回我设置的虚拟ip。。但是此时，浏览器却不能识别我的返回的DNS解析结果，显示DNS解析错误，下面是我的NSLookupServiceNext中返回结果的代码，求大佬指点一下迷津

`memset(lpqsResults, 0, sizeof(WSAQUERYSETW));
	lpqsResults->dwSize = 120;
	lpqsResults->dwNameSpace = NS_DNS;
	lpqsResults->dwNumberOfProtocols = 0;
	lpqsResults->dwNumberOfCsAddrs = 1;
	lpqsResults->dwOutputFlags = LUP_NEAREST | LUP_RETURN_PREFERRED_NAMES; //LUP_NEAREST
	lpqsResults->lpszQueryString = context->hostname;
	lpqsResults->lpszServiceInstanceName = context->hostname;
	lpqsResults->lpcsaBuffer = new CSADDR_INFO({ 0 });

	struct sockaddr_in6* localEP = new struct sockaddr_in6({ 0 });
	localEP->sin6_family = AF_INET6;
	struct sockaddr_in6* remoteEP = new struct sockaddr_in6({ 0 });
 	remoteEP->sin6_family = AF_INET6;

	struct in_addr inAddr;
	inAddr.S_un.S_addr = 16779364; //返回一个固定ip
	string resloveIP = "::ffff:";
	resloveIP.append(inet_ntoa(inAddr));
	if (inet_pton(AF_INET6, resloveIP.c_str(), &remoteEP->sin6_addr) == 1)
		Debugger::Write("##################### ip addr: %x", remoteEP->sin6_addr);

	context->localip = localEP;
	context->remoteip = remoteEP;

	CSADDR_INFO* addr = lpqsResults->lpcsaBuffer;
	addr->iSocketType = SOCK_RAW;
	addr->iProtocol = 23;
	addr->RemoteAddr.iSockaddrLength = sizeof(struct sockaddr_in6);
	addr->LocalAddr.iSockaddrLength = sizeof(struct sockaddr_in);
	addr->LocalAddr.lpSockaddr = (struct sockaddr*)localEP;
	addr->RemoteAddr.lpSockaddr = (struct sockaddr*)remoteEP;
	context->behavior = 1;
	return NO_ERROR;`

**Comment by wangquent** [comment]
还有一个问题，例如在浏览器键入某个在公网DNS下无解析的地址，感觉实际上系统是把所有的NSP都执行了一遍，（尤其是无解析的情况，一般要等到系统的解析超时）所以感觉十分缓慢，即使自己的NSP模块早已返回了结果，还是要等。。。这个有什么方法能够在自己的结果返回之后，不再去等待其他的NSP解析结果吗

**Comment by wangquent** [comment]
跪求大佬指点一下迷津，多谢！
还是不够理解NSP的机制，难道是要等所有的NSP提供者都完成解析之后，通过排序各个NSP的解析结果然后再返回？这样感觉好像又不符合逻辑，假如某一个NSP提供者无法针对某个域名进行解析，需要等待到超时，这样岂不是拖慢了整个的dns解析。。。。 所以感觉以API设计上来说应该不会这么设计才对
再次跪拜大佬  求解答一下疑惑  多谢

**Comment by UMU618** [comment]
确实是要等所有 NSP 都完成解析……
